# Form implementation generated from reading ui file 'E:\KI II\KTLT\Do_an\giaodien.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(502, 404)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 30, 291, 321))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pBtense = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pBtense.setFont(font)
        self.pBtense.setStyleSheet("QWidget {\n"
"    background-color: #e8f1f2; /* Màu vàng nhạt */\n"
"}\n"
"QPushButton {\n"
"    background-color: #23395d; /*mau xanh  */\n"
"    color: white; /* Chữ màu trắng */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 140, 0); /* Màu cam đậm khi hover */\n"
"}")
        self.pBtense.setObjectName("pBtense")
        self.verticalLayout.addWidget(self.pBtense)
        self.pBstruc = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pBstruc.setFont(font)
        self.pBstruc.setStyleSheet("QWidget {\n"
"    background-color: #e8f1f2; /* Màu vàng nhạt */\n"
"}\n"
"QPushButton {\n"
"    background-color: #23395d; /*mau xanh  */\n"
"    color: white; /* Chữ màu trắng */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 140, 0); /* Màu cam đậm khi hover */\n"
"}")
        self.pBstruc.setObjectName("pBstruc")
        self.verticalLayout.addWidget(self.pBstruc)
        self.pBdaily = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pBdaily.setFont(font)
        self.pBdaily.setStyleSheet("QWidget {\n"
"    background-color: #e8f1f2; /* Màu vàng nhạt */\n"
"}\n"
"QPushButton {\n"
"    background-color: #23395d; /*mau xanh  */\n"
"    color: white; /* Chữ màu trắng */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 140, 0); /* Màu cam đậm khi hover */\n"
"}")
        self.pBdaily.setObjectName("pBdaily")
        self.verticalLayout.addWidget(self.pBdaily)
        self.pBcommu = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pBcommu.setFont(font)
        self.pBcommu.setStyleSheet("QWidget {\n"
"    background-color: #e8f1f2; /* Màu vàng nhạt */\n"
"}\n"
"QPushButton {\n"
"    background-color: #23395d; /*mau xanh  */\n"
"    color: white; /* Chữ màu trắng */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 140, 0); /* Màu cam đậm khi hover */\n"
"}")
        self.pBcommu.setObjectName("pBcommu")
        self.verticalLayout.addWidget(self.pBcommu)
        self.pBidoms = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pBidoms.setFont(font)
        self.pBidoms.setStyleSheet("QWidget {\n"
"    background-color: #e8f1f2; /* Màu vàng nhạt */\n"
"}\n"
"QPushButton {\n"
"    background-color: #23395d; /*mau xanh  */\n"
"    color: white; /* Chữ màu trắng */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 140, 0); /* Màu cam đậm khi hover */\n"
"}")
        self.pBidoms.setObjectName("pBidoms")
        self.verticalLayout.addWidget(self.pBidoms)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 501, 341))
        self.label.setStyleSheet("background-color: rgb(222, 233, 255);\n"
"border-radius: 15px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.lblprofile = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblprofile.setGeometry(QtCore.QRect(290, 40, 201, 31))
        self.lblprofile.setStyleSheet("background-color: rgb(41, 85, 151);\n"
"border-radius: 15px; \n"
"border: rgb(0, 0, 0);")
        self.lblprofile.setObjectName("lblprofile")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(310, 90, 171, 241))
        self.label_2.setStyleSheet(" background-color: lightblue; \n"
"    border-radius: 15px; \n"
"    border: 2px solid blue; \n"
"    padding: 5px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(330, 200, 141, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 110, 121, 31))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label.raise_()
        self.verticalLayoutWidget.raise_()
        self.lblprofile.raise_()
        self.label_2.raise_()
        self.progressBar.raise_()
        self.label_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 502, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pBtense.setText(_translate("MainWindow", "TENSES IN ENGLISH"))
        self.pBstruc.setText(_translate("MainWindow", "OTHER STRUCTURES"))
        self.pBdaily.setText(_translate("MainWindow", "DAILY WORDS"))
        self.pBcommu.setText(_translate("MainWindow", "COMMUNICATION"))
        self.pBidoms.setText(_translate("MainWindow", "IDIOMS AND OTHERS"))
        self.lblprofile.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">Profile</span></p></body></html>"))
