# Form implementation generated from reading ui file 'E:\KI II\KTLT\Do_an\giaodien.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(464, 403)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_3.setStyleSheet("background-color:rgb(183, 205, 211);\n"
"border-radius: 15px; ")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pBtense = QtWidgets.QPushButton(parent=self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pBtense.setFont(font)
        self.pBtense.setStyleSheet("QWidget {\n"
"    background-color: #e8f1f2; /* Màu vàng nhạt */\n"
"}\n"
"QPushButton {\n"
"    background-color: #23395d; /*mau xanh  */\n"
"    color: white; /* Chữ màu trắng */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 140, 0); /* Màu cam đậm khi hover */\n"
"}")
        self.pBtense.setObjectName("pBtense")
        self.verticalLayout.addWidget(self.pBtense)
        self.pBstruc = QtWidgets.QPushButton(parent=self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pBstruc.setFont(font)
        self.pBstruc.setStyleSheet("QWidget {\n"
"    background-color: #e8f1f2; /* Màu vàng nhạt */\n"
"}\n"
"QPushButton {\n"
"    background-color: #23395d; /*mau xanh  */\n"
"    color: white; /* Chữ màu trắng */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 140, 0); /* Màu cam đậm khi hover */\n"
"}")
        self.pBstruc.setObjectName("pBstruc")
        self.verticalLayout.addWidget(self.pBstruc)
        self.pBdaily = QtWidgets.QPushButton(parent=self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pBdaily.setFont(font)
        self.pBdaily.setStyleSheet("QWidget {\n"
"    background-color: #e8f1f2; /* Màu vàng nhạt */\n"
"}\n"
"QPushButton {\n"
"    background-color: #23395d; /*mau xanh  */\n"
"    color: white; /* Chữ màu trắng */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 140, 0); /* Màu cam đậm khi hover */\n"
"}")
        self.pBdaily.setObjectName("pBdaily")
        self.verticalLayout.addWidget(self.pBdaily)
        self.pBcommu = QtWidgets.QPushButton(parent=self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pBcommu.setFont(font)
        self.pBcommu.setStyleSheet("QWidget {\n"
"    background-color: #e8f1f2; /* Màu vàng nhạt */\n"
"}\n"
"QPushButton {\n"
"    background-color: #23395d; /*mau xanh  */\n"
"    color: white; /* Chữ màu trắng */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 140, 0); /* Màu cam đậm khi hover */\n"
"}")
        self.pBcommu.setObjectName("pBcommu")
        self.verticalLayout.addWidget(self.pBcommu)
        self.pBidoms = QtWidgets.QPushButton(parent=self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pBidoms.setFont(font)
        self.pBidoms.setStyleSheet("QWidget {\n"
"    background-color: #e8f1f2; /* Màu vàng nhạt */\n"
"}\n"
"QPushButton {\n"
"    background-color: #23395d; /*mau xanh  */\n"
"    color: white; /* Chữ màu trắng */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 140, 0); /* Màu cam đậm khi hover */\n"
"}")
        self.pBidoms.setObjectName("pBidoms")
        self.verticalLayout.addWidget(self.pBidoms)
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(parent=self.frame)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 44, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Ignored)
        self.gridLayout.addItem(spacerItem, 3, 1, 1, 1)
        self.lblprofile = QtWidgets.QLabel(parent=self.widget)
        self.lblprofile.setStyleSheet("background-color: #13293d;\n"
"border-radius: 20px; \n"
"border: rgb(0, 0, 0);")
        self.lblprofile.setObjectName("lblprofile")
        self.gridLayout.addWidget(self.lblprofile, 1, 1, 1, 1)
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 280))
        self.widget_2.setStyleSheet(" background-color: lightblue; \n"
"    border-radius: 15px; \n"
"    border: 2px solid blue; \n"
"    padding: 5px;")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.lblname = QtWidgets.QLabel(parent=self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.lblname.setFont(font)
        self.lblname.setStyleSheet("background-color: #e0e0e0;\n"
"border-radius: 15px; ")
        self.lblname.setText("")
        self.lblname.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblname.setObjectName("lblname")
        self.verticalLayout_3.addWidget(self.lblname)
        self.label_6 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_6.setMinimumSize(QtCore.QSize(0, 48))
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.progressBar = QtWidgets.QProgressBar(parent=self.widget_2)
        self.progressBar.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.progressBar.setStyleSheet("QProgressBar {\n"
"        border: 3px solid #555;\n"
"        border-radius: 10px;\n"
"        background-color: #e0e0e0;\n"
"        text-align: center;\n"
"        font-size: 14pt;\n"
"        font-weight: bold;\n"
"        color: black;\n"
"    }\n"
"    QProgressBar::chunk {\n"
"        background: qlineargradient(\n"
"            spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"            stop:0 #ff0000, stop:0.5 #ffbf00, stop:1 #00ff00\n"
"        );\n"
"        border-radius: 8px;\n"
"    }")
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        self.label_7 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.lblscore = QtWidgets.QLabel(parent=self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblscore.setFont(font)
        self.lblscore.setStyleSheet("background-color: #e0e0e0;\n"
"border-radius: 15px; ")
        self.lblscore.setText("")
        self.lblscore.setObjectName("lblscore")
        self.verticalLayout_3.addWidget(self.lblscore)
        self.gridLayout.addWidget(self.widget_2, 4, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.widget)
        self.horizontalLayout.addWidget(self.frame)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 464, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pBtense.setText(_translate("MainWindow", "TENSES IN ENGLISH"))
        self.pBstruc.setText(_translate("MainWindow", "OTHER STRUCTURES"))
        self.pBdaily.setText(_translate("MainWindow", "DAILY WORDS"))
        self.pBcommu.setText(_translate("MainWindow", "COMMUNICATION"))
        self.pBidoms.setText(_translate("MainWindow", "IDIOMS AND OTHERS"))
        self.lblprofile.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600; color:#ffffff;\">Profile</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-style:italic; color:#000051;\">User:</span></p></body></html>"))
        self.lblname.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-style:italic; color:#000040;\">Progress:</span></p></body></html>"))
        self.progressBar.setFormat(_translate("MainWindow", "%p%"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-style:italic; color:#000040;\">Score:</span></p></body></html>"))
        self.lblscore.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
