# Form implementation generated from reading ui file 'E:\KI II\KTLT\Do_an\grammar2.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(575, 558)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QWidget {\n"
"    background-color: #e8f1f2; /* Màu vàng nhạt */\n"
"}\n"
"QPushButton {\n"
"    background-color: #23395d; /*mau xanh  */\n"
"    color: white; /* Chữ màu trắng */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 140, 0); /* Màu cam đậm khi hover */\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:\\KI II\\KTLT\\Do_an\\../../../icons8-play-48 - Copy.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.exerciseHeaderLabel = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.exerciseHeaderLabel.setFont(font)
        self.exerciseHeaderLabel.setStyleSheet("background-color: rgb(19, 41, 60);\n"
"color: #fff")
        self.exerciseHeaderLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.exerciseHeaderLabel.setObjectName("exerciseHeaderLabel")
        self.verticalLayout.addWidget(self.exerciseHeaderLabel)
        self.tenseSelectionLayout = QtWidgets.QHBoxLayout()
        self.tenseSelectionLayout.setObjectName("tenseSelectionLayout")
        self.tenseLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.tenseLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tenseLabel.setObjectName("tenseLabel")
        self.tenseSelectionLayout.addWidget(self.tenseLabel)
        self.tenseCombo = QtWidgets.QComboBox(parent=self.centralwidget)
        self.tenseCombo.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.tenseCombo.setFont(font)
        self.tenseCombo.setStyleSheet("background-color: rgb(85, 143, 174);\n"
"color: rgb(0, 0, 0);\n"
"font-weight: bold;\n"
"")
        self.tenseCombo.setObjectName("tenseCombo")
        self.tenseSelectionLayout.addWidget(self.tenseCombo)
        self.verticalLayout.addLayout(self.tenseSelectionLayout)
        self.tenseDetailsLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.tenseDetailsLabel.setMinimumSize(QtCore.QSize(0, 100))
        self.tenseDetailsLabel.setStyleSheet("background-color: #e8f1f2;\n"
"color: rgb(0, 0, 0);\n"
"font-weight: bold;\n"
"")
        self.tenseDetailsLabel.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.tenseDetailsLabel.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.tenseDetailsLabel.setText("")
        self.tenseDetailsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.tenseDetailsLabel.setWordWrap(True)
        self.tenseDetailsLabel.setObjectName("tenseDetailsLabel")
        self.verticalLayout.addWidget(self.tenseDetailsLabel)
        self.optionsBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.optionsBox.setFont(font)
        self.optionsBox.setStyleSheet("background-color: #e8f1f2;\n"
"color: rgb(0, 0, 0)")
        self.optionsBox.setObjectName("optionsBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.optionsBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.questionLabel = QtWidgets.QLabel(parent=self.optionsBox)
        self.questionLabel.setEnabled(True)
        self.questionLabel.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        self.questionLabel.setFont(font)
        self.questionLabel.setStyleSheet("background-color: #e8f1f;\n"
"color: rgb(0, 0, 0);\n"
"font-size: 14px;\n"
"")
        self.questionLabel.setText("")
        self.questionLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.questionLabel.setWordWrap(True)
        self.questionLabel.setObjectName("questionLabel")
        self.verticalLayout_2.addWidget(self.questionLabel)
        self.optionsWidget = QtWidgets.QWidget(parent=self.optionsBox)
        self.optionsWidget.setStyleSheet("color: #8A2BE2;\n"
"height: 26;\n"
"")
        self.optionsWidget.setObjectName("optionsWidget")
        self.optionsLayout = QtWidgets.QVBoxLayout(self.optionsWidget)
        self.optionsLayout.setObjectName("optionsLayout")
        self.verticalLayout_2.addWidget(self.optionsWidget)
        self.verticalLayout.addWidget(self.optionsBox)
        self.submitButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submitButton.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.submitButton.setFont(font)
        self.submitButton.setStyleSheet("QWidget {\n"
"    background-color: #2345rd ; /* Màu vàng nhạt */\n"
"    color: rgb(108, 27, 33);\n"
"}\n"
"QPushButton {\n"
"    background-color: #23395d; /*mau xanh  */\n"
"    color: white; /* Chữ màu trắng */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}")
        self.submitButton.setObjectName("submitButton")
        self.verticalLayout.addWidget(self.submitButton)
        self.feedbackLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.feedbackLabel.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setItalic(True)
        self.feedbackLabel.setFont(font)
        self.feedbackLabel.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.feedbackLabel.setText("")
        self.feedbackLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.feedbackLabel.setWordWrap(True)
        self.feedbackLabel.setObjectName("feedbackLabel")
        self.verticalLayout.addWidget(self.feedbackLabel)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setStyleSheet("QWidget {\n"
"    background-color: #e8f1f2; /* Màu vàng nhạt */\n"
"}\n"
"QPushButton {\n"
"    background-color: #23395d; /*mau xanh  */\n"
"    color: white; /* Chữ màu trắng */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(151, 178, 200); /* Màu xanh */\n"
"    color: white; /* Chữ màu trắng */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1c7bbf; /* Màu xanh đậm hơn khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #145c8c; /* Màu xanh tối khi nhấn */\n"
"}")
        self.pushButton.setText("")
        self.pushButton.setIcon(icon)
        self.pushButton.setCheckable(True)
        self.pushButton.setChecked(True)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(70, 10, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(151, 178, 200); /* Màu xanh */\n"
"    color: white; /* Chữ màu trắng */\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1c7bbf; /* Màu xanh đậm hơn khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #145c8c; /* Màu xanh tối khi nhấn */\n"
"}")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("E:\\KI II\\KTLT\\Do_an\\../../../icons8-play-48.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setChecked(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 575, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "English Tense Practice"))
        self.pushButton_3.setText(_translate("MainWindow", "Back"))
        self.exerciseHeaderLabel.setText(_translate("MainWindow", "OTHER STRUCTURES OF ENGLISH GRAMMAR"))
        self.tenseLabel.setText(_translate("MainWindow", "SELECT A STRUCTURE YOU WANT TO LEARN:"))
        self.optionsBox.setTitle(_translate("MainWindow", "Exercises"))
        self.submitButton.setText(_translate("MainWindow", "Submit Answer"))
